In [60]:
import torch

In [137]:
a = torch.tensor([2.,3])
print(a)
a = torch.nn.Parameter(a)  # allow gradient calculation
a3 = torch.tensor([4,6,7.,2])
a3 = torch.nn.Parameter(a3)  # allow gradient calculation
print("a3: ", a3)
print(a)
a1 = torch.FloatTensor([2,3])
print("a1: ", a1)
a1.requires_grad_()
print("a1 with grad: ", a1)
a1.requires_grad_(True)
print(a1.requires_grad)  # Bool
b = a+a * a
print(b.requires_grad)
a, b
b = a * a
print(b)
#a = a.detach()
print("a= ", a, ", a= ", a1, ", b= ", b)

tensor([2., 3.])
a3:  Parameter containing:
tensor([4., 6., 7., 2.], requires_grad=True)
Parameter containing:
tensor([2., 3.], requires_grad=True)
a1:  tensor([2., 3.])
a1 with grad:  tensor([2., 3.], requires_grad=True)
True
True
tensor([4., 9.], grad_fn=<MulBackward0>)
a=  Parameter containing:
tensor([2., 3.], requires_grad=True) , a=  tensor([2., 3.], requires_grad=True) , b=  tensor([4., 9.], grad_fn=<MulBackward0>)


In [138]:
c = torch.sum(b)
print(c)

tensor(13., grad_fn=<SumBackward0>)


In [140]:
c = torch.sum(b)
# Cannot run c.backward() two times in a row
if a.grad != None:
    a.grad.zero_()
c.backward(retain_graph=True)

1 a.grad:  None


AttributeError: 'NoneType' object has no attribute 'zero_'

In [49]:
a.grad, b.grad

<ipython-input-49-2388778a1c1d>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  a.grad, b.grad


(None, None)

* Can only take derivatives with respect to leaves. 
* Since $b$ depends on $a$, I can only compute the gradient with respect to $a$. 
* To compute the gradient with respect to $b$, I have to cut off the gradient propagation at $b$. HOW TO DO THIS? 

In [50]:
a

tensor([2., 3.])

In [51]:
b

tensor([4., 9.], grad_fn=<MulBackward0>)

In [52]:
c

tensor(13., grad_fn=<SumBackward0>)