## Imports 

In [1]:
import torch
import numpy as np

## Data

In [2]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

In [3]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [4]:
print(inputs)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])


In [5]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])


## Dataset

In [6]:
from torch.utils.data import TensorDataset

dataset = TensorDataset(inputs, targets)

In [7]:
dataset[:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

## DataLoader

In [8]:
from torch.utils.data import DataLoader

batch_size = 3
train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

In [9]:
# A Batch Sample
for inp,target in train_loader:
    print(inp)
    print(target)
    break

tensor([[74., 66., 43.],
        [69., 96., 70.],
        [91., 87., 65.]])
tensor([[ 57.,  69.],
        [103., 119.],
        [ 80., 102.]])


## Linear Regression

In [10]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.2889,  1.3758, -0.3526],
        [ 0.1972,  0.3231,  0.2537]], requires_grad=True)
tensor([ 0.2265, -0.2737], requires_grad=True)


In [11]:
def model(X):
    return X @ w.t() + b

In [12]:
for x,y in train_loader:
    preds = model(x)
    print("Prediction is :\n",preds)
    print("\nActual targets is :\n",y)
    break

Prediction is :
 tensor([[ 76.8878,  43.2507],
        [123.2839,  62.2739],
        [ 97.2398,  46.5545]], grad_fn=<AddBackward0>)

Actual targets is :
 tensor([[ 21.,  38.],
        [ 80., 102.],
        [ 57.,  69.]])


### Loss

In [13]:
def mse_loss(predictions, targets):
    difference = predictions - targets
    return torch.sum(difference * difference) / difference.numel()

In [14]:
for x,y in train_loader:
    preds = model(x)
    print("Prediction is :\n",preds)
    print("\nActual targets is :\n",y)
    print("\nLoss is: ",mse_loss(preds, y))
    break

Prediction is :
 tensor([[ 76.4423,  43.0684],
        [123.9254,  62.2175],
        [ 97.2398,  46.5545]], grad_fn=<AddBackward0>)

Actual targets is :
 tensor([[ 20.,  38.],
        [ 82., 100.],
        [ 57.,  69.]])

Loss is:  tensor(1419.9540, grad_fn=<DivBackward0>)


In [15]:
epochs = 50
for i in range(epochs):
    # Iterate through training dataloader
    for x,y in train_loader:
        # Generate Prediction
        preds = model(x)
        # Get the loss and perform backpropagation
        loss = mse_loss(preds, y)
        loss.backward()
        # print(loss)
        # Let's update the weights
        with torch.no_grad():
            w -= w.grad *1e-5
            b -= b.grad * 1e-5
            # Set the gradients to zero
            w.grad.zero_()
            b.grad.zero_()
    print(f"Epoch {i}/{epochs}: Loss: {loss}")

Epoch 0/50: Loss: 728.4745483398438
Epoch 1/50: Loss: 367.2543029785156
Epoch 2/50: Loss: 292.3853759765625
Epoch 3/50: Loss: 152.8395233154297
Epoch 4/50: Loss: 115.80294799804688
Epoch 5/50: Loss: 454.1225280761719
Epoch 6/50: Loss: 322.7727355957031
Epoch 7/50: Loss: 352.5608825683594
Epoch 8/50: Loss: 304.7715759277344
Epoch 9/50: Loss: 277.3539123535156
Epoch 10/50: Loss: 60.40011978149414
Epoch 11/50: Loss: 192.6470184326172
Epoch 12/50: Loss: 149.48106384277344
Epoch 13/50: Loss: 167.32679748535156
Epoch 14/50: Loss: 124.42317962646484
Epoch 15/50: Loss: 143.9129638671875
Epoch 16/50: Loss: 213.5840301513672
Epoch 17/50: Loss: 211.6987762451172
Epoch 18/50: Loss: 212.7648468017578
Epoch 19/50: Loss: 24.273561477661133
Epoch 20/50: Loss: 158.4571990966797
Epoch 21/50: Loss: 96.69017791748047
Epoch 22/50: Loss: 175.9143524169922
Epoch 23/50: Loss: 119.3244857788086
Epoch 24/50: Loss: 112.75337982177734
Epoch 25/50: Loss: 98.65904998779297
Epoch 26/50: Loss: 124.75748443603516
Epoc

## Results

In [ ]:
for x,y in train_loader:
    preds = model(x)
    print("Prediction is :\n",preds)
    print("\nActual targets is :\n",y)
    break

Prediction is :
 tensor([[102.6596, 110.3845],
        [ 81.1419,  95.7303],
        [ 56.8479,  70.9188]], grad_fn=<AddBackward0>)

Actual targets is :
 tensor([[103., 119.],
        [ 82., 100.],
        [ 56.,  70.]])
